import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MyAppBar from '@/components/MyAppBar/MyAppBar';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import {theme} from "@/utils/Theme";
import { Paper } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme} >
          <Paper>

          <MyAppBar />
        {children}
        </Paper>
          </ThemeProvider>

        </AppRouterCacheProvider>
        </body>
    </html>
  );
}
